import type { ConfirmedInterfaceIconMapping } from "./confirmed-interface-icon-mapping.js";
import { linearIconData, type LinearIconName } from "./linear-icon-catalog.js";

export type InterfaceIconName =
	| "brain"
	| "bug"
	| "check"
	| "chevron-down"
	| "chevron-left"
	| "chevron-right"
	| "chevron-up"
	| "chat"
	| "clock"
	| "close"
	| "copy"
	| "copy-id"
	| "database"
	| "discord"
	| "edit"
	| "filter"
	| "github"
	| "image"
	| "lock"
	| "more"
	| "open-in-new-window"
	| "palette"
	| "plus"
	| "question"
	| "refresh"
	| "recycle"
	| "robot"
	| "save"
	| "search"
	| "send"
	| "settings-general"
	| "settings-skills"
	| "skills"
	| "moon"
	| "sun"
	| "terminal"
	| "trash"
	| "wrench";

export type InterfaceIconGlyph = {
	readonly viewBox: string;
	readonly inner: string;
};

export const interfaceIconMappings = {
	brain: {
		linearName: "brain",
		surface: "Linear brain/thinking icon",
		controlLabel: "Brain",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "5a89616c97d636739594ee554cb7345f124d19adef1e3ab8d139b387dcfd2d7d",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Brain",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	bug: {
		linearName: "bug",
		surface: "Linear bug icon",
		controlLabel: "Bug",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "b297a6be71993f33c2103cdc7edca62ee0719f97db8e5aa5601217ceab7e0e22",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Bug",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	check: {
		linearName: "check",
		surface: "Linear checkmark control",
		controlLabel: "Check",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "fa6077227edaff7aeab4adff5638f955fcfd5830fe5e1fe8c7aeff467a2d28cd",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "CheckIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"chevron-down": {
		linearName: "chevron-down",
		surface: "Linear chevron down control",
		controlLabel: "Chevron Down",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "0dd291dfd61fe9e5e5f7f19e944636bea4a33a45862a650b6d6340fb59516f30",
		sourceChunk: "ChevronDownIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "ChevronDownIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"chevron-left": {
		linearName: "chevron-left",
		surface: "Linear chevron left control",
		controlLabel: "Chevron Left",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "d80ae4c6d05528bd972aa66a6f0cab7f38bc698d5272a645f4d4933ca484bd17",
		sourceChunk: "ChevronLeftIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "ChevronLeftIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"chevron-right": {
		linearName: "chevron-right",
		surface: "Linear chevron right control",
		controlLabel: "Chevron Right",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "61437bc796a7eadd84c49d9352c2f511ae31eb569b3331e015ca78dbb606de11",
		sourceChunk: "ChevronRightIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "ChevronRightIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"chevron-up": {
		linearName: "chevron-up",
		surface: "Linear chevron up control",
		controlLabel: "Chevron Up",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "c2183ab64a07b67796ad7aebf6bd114ceeb5e8b43cb9f36bcc42ab3205cee8c3",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "ChevronUpIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	chat: {
		linearName: "chat",
		surface: "Linear chat icon",
		controlLabel: "Chat",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "ae86db49a03c610d46320269d37d77153a6cf8dea1a23c437df469e375677d30",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Chat",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	clock: {
		linearName: "clock",
		surface: "Linear clock icon",
		controlLabel: "Clock",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "8be3439333064696b7116cb549b8f225446b7c4dbba2af118aeea2b7efa99a8d",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Clock",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	close: {
		linearName: "close",
		surface: "Linear close control",
		controlLabel: "Close",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "65d9582f8976d6d5f455163cef549f6f1902ba2f19c4d60fa947bdd4b766c0ac",
		sourceChunk: "CloseIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "CloseIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	copy: {
		linearName: "copy",
		surface: "Linear generic copy control",
		controlLabel: "Copy",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "8632fdbd4585428b90773ccdb756965f16bef6461dc91ac26bd3be893c425fae",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "CopyIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"copy-id": {
		linearName: "copy-id",
		surface: "Linear issue copy menu",
		controlLabel: "Copy ID",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "b854153cf446f3c0af933b1b349771bf9107b80ae3dcbfe8add65e7040530e73",
		sourceChunk: "AgentToolbarActions",
		sourceType: "feature-jsx",
		sourceSet: null,
		originalName: "CopyIdIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	database: {
		linearName: "database",
		surface: "Linear database icon",
		controlLabel: "Database",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "d5e207a33174cedd4f63bf077e077c301c4596799ee83060bd55f93445655e9d",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Database",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	discord: {
		linearName: "discord",
		surface: "Linear Discord brand icon",
		controlLabel: "Discord",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "d2668478df52f787e26753e07007daff67ca3c553785db307c703c7ec53cb489",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Discord",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	edit: {
		linearName: "edit",
		surface: "Linear edit control",
		controlLabel: "Edit",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "28203812ab6b80ad0ca13a4b1aee18697149a4dba76f300614f3d65f8e3405a9",
		sourceChunk: "EditorActions",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "EditIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	filter: {
		linearName: "filter",
		surface: "Linear filter control",
		controlLabel: "Filter",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "0d58a4864a6db0083555c47de6f5049392f78183faa54e39345a24bb98ff43b5",
		sourceChunk: "FilterIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "FilterIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	github: {
		linearName: "git-hub",
		surface: "Linear GitHub brand icon",
		controlLabel: "GitHub",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "75dcd4cc0f2d722f1a6ce88e063ae55bcf590c31aca0342a7e9a13088d2f4a99",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "brands",
		originalName: "GitHub",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	image: {
		linearName: "image",
		surface: "Linear image icon",
		controlLabel: "Image",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "3458ed501795d761cfc79eed636a089f460797b457d4b3b49923168cf29bc4ac",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Image",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	lock: {
		linearName: "lock",
		surface: "Linear lock control",
		controlLabel: "Lock",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "9b4a60cb73bd39cde05b2a023955a5de58cf9905082bb2e6e4dfb2f07c7dc4d1",
		sourceChunk: "LockIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "LockIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	more: {
		linearName: "horizontal-ellipsis",
		surface: "Linear overflow/more menu control",
		controlLabel: "More",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "44ae30213e2ab91c35580ebc6194346d8c0be9bd48c3f09d8b1fa92748bf5534",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "FeatureSvg5cb3b1ac95c4Icon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	moon: {
		linearName: "moon",
		surface: "Linear moon theme icon",
		controlLabel: "Moon",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "0652bd3f317abb135a8bb792d7db1d1e39c1ac9f2be1943541473bdbfa950211",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Moon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"open-in-new-window": {
		linearName: "open-in-new-window",
		surface: "Linear external navigation control",
		controlLabel: "Open in new window",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "2fc899fe45cce78a3ba453de611bf5f80fde51db37e34c7b0887e63b3854b36c",
		sourceChunk: "AgentToolbarActions",
		sourceType: "feature-jsx",
		sourceSet: null,
		originalName: "OpenInNewWindowIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	palette: {
		linearName: "paint",
		surface: "Linear appearance/customization icon",
		controlLabel: "Appearance",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "ecbfb0c9fba802978df82aa04608b36db562418ea9bb60c94932996a7e4b8df1",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Paint",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	plus: {
		linearName: "plus",
		surface: "Linear add/create control",
		controlLabel: "Plus",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "0a168498f50baa978f61243d754a654805917719ce2bc6d0e7bef9724d5fd47f",
		sourceChunk: "PlusIcon",
		sourceType: "dedicated-chunk",
		sourceSet: null,
		originalName: "PlusIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	question: {
		linearName: "question-mark",
		surface: "Linear question mark icon",
		controlLabel: "Question",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "ecc9715042719437fc1da587548fcfd91a59e31302d0b1abffae330ccbb01758",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "QuestionMark",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	refresh: {
		linearName: "refresh",
		surface: "Linear refresh control",
		controlLabel: "Refresh",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "8baab114e17a8cb35b54c8ee65cf38e200cdbbf3476804d84dc1e088a276d569",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "base",
		originalName: "Refresh",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	recycle: {
		linearName: "recycle",
		surface: "Linear recycle/refactor icon",
		controlLabel: "Recycle",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "d09f649fd7e2a3fff30e91bc7862d15981268708a1f3951a85f8b9a89ee742b5",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Recycle",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	robot: {
		linearName: "robot",
		surface: "Linear robot/agent icon",
		controlLabel: "Robot",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "5ab1d63dcd3613250814830015d91c7052a9669dfab1b27b673de6efb36206e5",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Robot",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	save: {
		linearName: "floppy-disk",
		surface: "Linear save icon",
		controlLabel: "Save",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "161bd96d2b49104d0afe848b116396d82fe236d18742ed70a56e9229b9d86871",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "FloppyDisk",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	search: {
		linearName: "search",
		surface: "Linear search control",
		controlLabel: "Search",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "1fbddf08f27ed2b3d262ccc4d5a1096b6014786a3e1221c9975ca1000976f7b6",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "base",
		originalName: "Search",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	send: {
		linearName: "send",
		surface: "Linear send control",
		controlLabel: "Send",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "0720d38034c36a64ead53f5d4c6f6c8224e4953e2e676b1eb7a5c0488995ca67",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "base",
		originalName: "Send",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"settings-general": {
		linearName: "feature-svg6bdd3b6f165e",
		surface: "Linear workspace settings",
		controlLabel: "General",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "1eee9fc1558004de2bf7731f766f869fc3fcefef1495580b8764afc2ad8b4a6b",
		sourceChunk: "RegisterAction",
		sourceType: "feature-jsx",
		sourceSet: null,
		originalName: "FeatureSvg6bdd3b6f165eIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	"settings-skills": {
		linearName: "skills",
		surface: "Linear agent settings",
		controlLabel: "Skills",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-control-binding",
		geometryHash: "040efb1f00407cb059ed43046057958f154588bb4b6a21cedc936402887fe560",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "SkillsIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	skills: {
		linearName: "skills",
		surface: "Linear skills icon",
		controlLabel: "Skills",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "040efb1f00407cb059ed43046057958f154588bb4b6a21cedc936402887fe560",
		sourceChunk: "useIsMounted",
		sourceType: "shared-jsx",
		sourceSet: null,
		originalName: "SkillsIcon",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	sun: {
		linearName: "sun",
		surface: "Linear sun theme icon",
		controlLabel: "Sun",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "91397147cab3c92a4b174e925125d6b72e6c78542c59bb712c4e3260c05de072",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Sun",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	terminal: {
		linearName: "terminal",
		surface: "Linear terminal icon",
		controlLabel: "Terminal",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "e738bfdbf9c01052ac9df56065159dd2e5fd5e7145690cd78bd56251aaf390a5",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Terminal",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	trash: {
		linearName: "trash",
		surface: "Linear trash/delete control",
		controlLabel: "Trash",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "032ad6a91366f029e89a7df2c0adcd917c8577395aae9b9e89caef9864c8a0af",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Trash",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
	wrench: {
		linearName: "wrench",
		surface: "Linear wrench/tooling icon",
		controlLabel: "Wrench",
		observedBuild: "1.31.1",
		observationMethod: "linear-bundle-semantic-export",
		geometryHash: "84c11d0e6c788aa976d8878b40b24fad38ceade8b685dc4d6b3fd51b4ffa4c05",
		sourceChunk: "Root",
		sourceType: "symbol-sprite",
		sourceSet: "decorative",
		originalName: "Wrench",
		evidenceState: "approved",
		categoryExceptionReason: null,
	},
} as const satisfies Record<InterfaceIconName, ConfirmedInterfaceIconMapping>;

export function getInterfaceIconEvidence(
	name: InterfaceIconName,
): ConfirmedInterfaceIconMapping {
	return interfaceIconMappings[name];
}

export function resolveInterfaceIconGlyph(
	name: InterfaceIconName,
): InterfaceIconGlyph {
	const evidence = getInterfaceIconEvidence(name);
	const iconName: LinearIconName = evidence.linearName;
	return linearIconData[iconName];
}
