import type { LinearIconName } from "./linear-icon-catalog.js";
import type { RoundedIconName } from "./rounded-icon-data.generated.js";

/**
 * Best-effort mapping from Acepe RoundedIcon names to Linear inventory icons.
 *
 * Entries in `acepeOnly` should keep rendering the Acepe rounded SVG when a
 * pixel-accurate or brand-specific glyph is required. Brand icons may still
 * have a semantic Linear counterpart listed in `roundedToLinear`.
 */
export const roundedToLinearMap = {
	"rounded-to-linear": {
		add: "add-relation",
		alert: "alert",
		animated: "animated-arrow-up-down",
		"app-window": "desktop-window",
		apps: "spaces",
		appshot: "view-finder",
		archive: "box-open",
		"arrow-counter-clockwise": "refresh",
		"arrow-left": "back",
		"arrow-right": "chevron-right",
		"arrow-top-right": "direction",
		"arrow-up-right": "direction",
		"arrow-up": "animated-arrow-up-down",
		automations: "automation",
		avatar: "current-user",
		brain: "brain",
		branch: "subgroup",
		bug: "bug",
		building: "factory",
		"chart-line": "chart",
		chat: "chat",
		chats: "conversation",
		"check-circle-filled": "issue-status-done",
		"check-circle": "resolved",
		check: "checklist",
		"chevron-down": "chevron-down",
		"chevron-left": "chevron-left",
		"chevron-right": "chevron-right",
		"chevron-up": "chevron",
		chrome: "chrome",
		"circle-dashed": "empty-circle",
		clock: "clock",
		close: "close",
		cloud: "cloud",
		code: "code-block",
		collapse: "close-tabs",
		comment: "comment",
		compose: "write",
		connected: "connected",
		copy: "scissors",
		cursor: "cursor",
		"diff-backgrounds": "diagram",
		"diff-bars": "bar-graph",
		"diff-classic": "diagram",
		"diff-line-numbers": "text-block",
		"diff-wrapping": "text-paragraph",
		dock: "close-tabs-variant2",
		document: "page",
		download: "inbox",
		drag: "pointer",
		edit: "write",
		empty: "empty-inbox",
		expand: "direction",
		"external-link": "routing",
		"eye-off": "eye-strikethrough",
		eye: "view-finder",
		face: "face",
		"file-text": "text-block",
		filter: "filter",
		first: "rank",
		flask: "chemist",
		folder: "folder",
		folders: "file-tree",
		format: "text-paragraph",
		"git-diff-unified": "diagram",
		"git-diff": "diagram",
		git: "inherited",
		github: "git-hub",
		globe: "world",
		"google-drive": "google-play",
		gpu: "chip",
		graduation: "education",
		hand: "click-button",
		"heart-filled": "heart",
		heart: "heart",
		history: "updated",
		homepage: "home",
		image: "image",
		info: "question-mark",
		keyboard: "command",
		laptop: "computer",
		lightning: "bolt",
		link: "link",
		lock: "lock",
		log: "report",
		macbook: "mac",
		mcp: "linear-ai",
		members: "members",
		microphone: "mic",
		minus: "close",
		more: "status",
		"new-chat": "chat-line",
		notebook: "note-pad",
		openai: "open-ai",
		paged: "book-open",
		"paper-plane": "send",
		pencil: "write",
		permissions: "policy",
		phone: "phone",
		plan: "initiative",
		"play-outline": "video",
		play: "video",
		plus: "plus",
		pop: "routing",
		"pull-request-closed": "pull-request-status-variant4",
		"pull-request-merged": "pull-request-status-variant2",
		"pull-request": "pull-request-status",
		"question-circle": "question-mark",
		realtime: "notified",
		referral: "present",
		refresh: "refresh",
		regenerate: "recycle",
		review: "issue-status-review",
		search: "search",
		send: "send",
		settings: "gears",
		share: "megaphone",
		"shield-check": "shield",
		"shield-code": "hack",
		"shield-warning": "safety-kit",
		"sidebar-open": "close-tabs",
		sidebar: "close-tabs-variant2",
		skills: "design-tools",
		sliders: "filter",
		sparkle: "magic-wand",
		speedometer: "speedometer",
		spinner: "process",
		star: "starred",
		stop: "cross",
		sun: "sun",
		tasks: "checklist",
		team: "team",
		terminal: "terminal",
		"tool-browser": "world",
		"tool-edit": "write",
		"tool-plan": "initiative",
		"tool-read": "book-open",
		"tool-search": "search",
		"tool-skill": "design-tools",
		"tool-sql": "database",
		"tool-task": "checklist",
		"tool-think": "brain",
		"tool-web": "world",
		trash: "trash",
		undo: "reset",
		unselected: "empty-circle",
		warning: "exclamation-mark",
		worktree: "file-tree",
		"x-circle-filled": "cross",
		"x-circle": "cross",
		bell: "alarm",
		browser: "world",
		files: "file-tree",
		moon: "moon",
		question: "question-mark",
		"settings-cog": "gears",
		"sidebar-closed": "close-tabs-variant2",
		three: "status",
	} satisfies Record<RoundedIconName, LinearIconName>,

	"acepe-only": [
		"github",
		"openai",
		"google-drive",
		"copy",
		"download",
		"minus",
		"stop",
		"play-outline",
		"diff-backgrounds",
		"diff-bars",
		"diff-classic",
		"diff-line-numbers",
		"diff-wrapping",
		"git-diff-unified",
		"git-diff",
	] as const satisfies readonly RoundedIconName[],

	notes: {
		add: "No exact 'add' icon; add-relation is the closest create/link affordance.",
		animated: "Rounded animated glyph maps to Linear animated-arrow-up-down.",
		apps: "App grid maps to Linear spaces (workspace/app launcher).",
		appshot: "Screenshot frame is Acepe-specific; view-finder is the closest capture metaphor.",
		archive: "No archive icon; box-open suggests stored/closed container.",
		"arrow-counter-clockwise": "Counter-clockwise refresh arrow maps to refresh.",
		"arrow-left": "Navigation back arrow maps to back.",
		"arrow-right": "Forward arrow maps to chevron-right.",
		"arrow-top-right": "Diagonal outbound arrow maps to direction.",
		"arrow-up-right": "Diagonal outbound arrow maps to direction.",
		"arrow-up": "Up arrow maps to animated-arrow-up-down (only vertical arrow variant).",
		avatar: "User avatar maps to current-user.",
		branch: "Git branch maps to subgroup (branch/fork tree).",
		building: "Building/office maps to factory.",
		"chart-line": "Line chart maps to chart.",
		chats: "Multiple chats maps to conversation.",
		"check-circle-filled": "Filled success circle maps to issue-status-done.",
		"check-circle": "Outlined success circle maps to resolved.",
		check: "Checkmark maps to checklist.",
		"chevron-up": "No chevron-up; generic chevron is closest upward caret.",
		"circle-dashed": "Dashed selection ring maps to empty-circle.",
		collapse: "Panel collapse maps to close-tabs.",
		compose: "Compose/new message maps to write.",
		copy: "No copy/duplicate icon in Linear inventory; scissors is adjacent edit action.",
		"diff-backgrounds": "Diff view mode is Acepe-specific; diagram is weak fallback only.",
		"diff-bars": "Diff view mode is Acepe-specific; bar-graph is weak fallback only.",
		"diff-classic": "Diff view mode is Acepe-specific; diagram is weak fallback only.",
		"diff-line-numbers": "Diff view mode is Acepe-specific; text-block is weak fallback only.",
		"diff-wrapping": "Diff view mode is Acepe-specific; text-paragraph is weak fallback only.",
		dock: "Docked panel maps to close-tabs-variant2.",
		document: "Generic document maps to page.",
		download: "No download icon in Linear inventory; inbox is weak receive fallback.",
		edit: "Edit pencil maps to write.",
		empty: "Empty state maps to empty-inbox.",
		expand: "Expand/open maps to direction.",
		"external-link": "External navigation maps to routing.",
		eye: "No plain eye icon; view-finder covers preview/visibility.",
		"file-text": "Text file maps to text-block.",
		first: "Jump to first maps to rank (ordering).",
		flask: "Lab/experiment maps to chemist.",
		folders: "Multiple folders maps to file-tree.",
		format: "Text formatting maps to text-paragraph.",
		"git-diff-unified": "Unified diff view is Acepe-specific; diagram is weak fallback only.",
		"git-diff": "Split diff view is Acepe-specific; diagram is weak fallback only.",
		git: "Generic git maps to inherited (branch lineage).",
		github: "Brand glyph; git-hub exists but Acepe rounded icon should remain fallback.",
		globe: "Browser/world globe maps to world.",
		"google-drive": "Brand/service icon; google-play is nearest Google brand asset.",
		gpu: "GPU/compute maps to chip.",
		graduation: "Graduation cap maps to education.",
		hand: "Pointer/hand interaction maps to click-button.",
		"heart-filled": "Filled heart reuses heart (fill handled by styling).",
		history: "History/recents maps to updated.",
		homepage: "Homepage maps to home.",
		info: "Info circle maps to question-mark (closest help/info affordance).",
		keyboard: "Keyboard shortcuts map to command.",
		laptop: "Laptop device maps to computer.",
		lightning: "Lightning bolt maps to bolt.",
		log: "Activity log maps to report.",
		macbook: "MacBook maps to mac.",
		mcp: "MCP integration maps to linear-ai.",
		minus: "No minus/subtract icon; close is weak fallback only.",
		more: "Overflow menu maps to status.",
		"new-chat": "New chat maps to chat-line.",
		notebook: "Notebook maps to note-pad.",
		openai: "Brand glyph; open-ai exists but Acepe rounded icon should remain fallback.",
		paged: "Paged document maps to book-open.",
		"paper-plane": "Send message maps to send.",
		pencil: "Pencil edit maps to write.",
		permissions: "Permissions map to policy.",
		plan: "Planning maps to initiative.",
		"play-outline": "Outlined play is Acepe-specific; video is weak fallback only.",
		play: "Play action maps to video.",
		pop: "Pop-out window maps to routing.",
		"pull-request-closed": "Closed PR maps to pull-request-status-variant4.",
		"pull-request-merged": "Merged PR maps to pull-request-status-variant2.",
		"pull-request": "Pull request maps to pull-request-status.",
		realtime: "Live/realtime updates map to notified.",
		referral: "Referral/gift maps to present.",
		regenerate: "Regenerate maps to recycle.",
		review: "Review state maps to issue-status-review.",
		settings: "Settings cog maps to gears.",
		share: "Share action maps to megaphone.",
		"shield-check": "Verified shield maps to shield.",
		"shield-code": "Code/security shield maps to hack.",
		"shield-warning": "Warning shield maps to safety-kit.",
		"sidebar-open": "Open sidebar maps to close-tabs.",
		sidebar: "Sidebar maps to close-tabs-variant2.",
		skills: "Skills map to design-tools.",
		sliders: "Slider controls map to filter (adjustment metaphor).",
		sparkle: "Sparkle/AI magic maps to magic-wand.",
		spinner: "Loading spinner maps to process.",
		star: "Star/favorite maps to starred.",
		stop: "No stop icon; cross is weak fallback only.",
		tasks: "Tasks map to checklist.",
		"tool-browser": "Browser tool maps to world.",
		"tool-edit": "Edit tool maps to write.",
		"tool-plan": "Plan tool maps to initiative.",
		"tool-read": "Read tool maps to book-open.",
		"tool-search": "Search tool maps to search.",
		"tool-skill": "Skill tool maps to design-tools.",
		"tool-sql": "SQL tool maps to database.",
		"tool-task": "Task tool maps to checklist.",
		"tool-think": "Think tool maps to brain.",
		"tool-web": "Web tool maps to world.",
		undo: "Undo maps to reset.",
		unselected: "Unselected radio/check maps to empty-circle.",
		warning: "Warning maps to exclamation-mark.",
		worktree: "Git worktree maps to file-tree.",
		"x-circle-filled": "Dismiss filled circle maps to cross.",
		"x-circle": "Dismiss circle maps to cross.",
		bell: "Alias for automations; alarm is closer bell/notification semantics.",
		browser: "Alias for globe; browser maps to world.",
		files: "Alias for folders; files maps to file-tree.",
		moon: "Alias for gpu; moon maps to moon (Acepe gpu icon is moon-shaped).",
		question: "Alias for question-circle; maps to question-mark.",
		"settings-cog": "Alias for settings; maps to gears.",
		"sidebar-closed": "Alias for sidebar; maps to close-tabs-variant2.",
		three: "Alias for more; overflow menu maps to status.",
	} satisfies Partial<Record<RoundedIconName, string>>,
} satisfies {
	"rounded-to-linear": Record<RoundedIconName, LinearIconName>;
	"acepe-only": readonly RoundedIconName[];
	notes: Partial<Record<RoundedIconName, string>>;
};

export type RoundedToLinearMap = typeof roundedToLinearMap;

export type AcepeOnlyRoundedIconName = (typeof roundedToLinearMap)["acepe-only"][number];

export function mapRoundedIconToLinear(name: RoundedIconName): LinearIconName {
	return roundedToLinearMap["rounded-to-linear"][name];
}

export function isAcepeOnlyRoundedIcon(name: RoundedIconName): name is AcepeOnlyRoundedIconName {
	return roundedToLinearMap["acepe-only"].includes(name as AcepeOnlyRoundedIconName);
}

export function roundedToLinearNote(name: RoundedIconName): string | undefined {
	const notes: Partial<Record<RoundedIconName, string>> = roundedToLinearMap.notes;
	return notes[name];
}
