export const DOTMATRIX_REGISTRY_MANIFEST = [
  { id: "dotm-square-1", label: "Neon Drift", description: "Same ripple family as the icon, with a wave that sweeps from the top-right toward the bottom-left." },
  { id: "dotm-square-2", label: "Pulse Ladder", description: "Clockwise snake route: starts bottom-left up column 1, jumps to column 3 down, then column 2 up, and continues the same cycle to the right." },
  { id: "dotm-square-3", label: "Core Spiral", description: "A 4-dot tail spirals clockwise from the outer border toward the center of the 5x5 grid." },
  { id: "dotm-square-4", label: "Twin Orbit", description: "Outer ring snake moves clockwise, middle ring snake moves anticlockwise, and the center dot stays inactive." },
  { id: "dotm-square-5", label: "Prism Sweep", description: "Snake-style trail that traverses the 5x5 grid on alternating diagonals." },
  { id: "dotm-square-6", label: "Flux Columns", description: "Five simultaneous snakes: columns 1/3/5 move up while columns 2/4 move down." },
  { id: "dotm-square-7", label: "Block Drop", description: "Tetromino-like frames drop and stack in a 5x5 matrix, then flash a row-clear beat." },
  { id: "dotm-square-8", label: "Strobe Stack", description: "Each column stacks upward on a stagger (Tetris-style), the full grid blinks twice, then columns drain downward with the same stagger." },
  { id: "dotm-square-9", label: "Glyph Pulse", description: "Two synced 2\u00d73 cells (Unicode dot order) step through clear motifs: rails, full grid, three rows, checker, horseshoes, and alternating columns." },
  { id: "dotm-square-10", label: "CRT Glide", description: "A CRT-style horizontal scanline moves down the matrix; swept rows leave a soft phosphor trail with a slight column-wise warp." },
  { id: "dotm-square-11", label: "Echo Ring", description: "Concentric diamond ripple with a soft secondary echo pulse per ring." },
  { id: "dotm-square-12", label: "Origin Wave", description: "Ripple starts at cell (2,2) and expands outward in concentric rings." },
  { id: "dotm-square-13", label: "Core Rotor", description: "Single fan blade rotating around a center hub for a clean, readable loop." },
  { id: "dotm-square-14", label: "Prism Bloom", description: "A symmetric kaleidoscope bloom cycling through clean radial motifs." },
  { id: "dotm-square-15", label: "Helix Glow", description: "Two mirrored strands with periodic bridges pulse like a compact DNA helix." },
  { id: "dotm-square-16", label: "Helix Core", description: "A narrower helix variant that stays in the center band while preserving strand/rung rhythm." },
  { id: "dotm-square-17", label: "Half Helix", description: "Single-strand helix variant that shows one side of the DNA wave." },
  { id: "dotm-square-18", label: "Sound Bars", description: "Equalizer-style vertical bars that pulse like live music levels." },
  { id: "dotm-square-19", label: "Infinity Run", description: "Dual counter-rotating heads trace a figure-eight with a soft crossover pulse at center." },
  { id: "dotm-square-20", label: "Mobius Run", description: "A bright head and tail run around the outer ring; a dimmer second train stays half a lap behind, with inner corner flashes for the twist." },
  { id: "dotm-circular-1", label: "Halo Drift", description: "A circular-masked half-helix that travels diagonally from top-left to bottom-right with a bright strand and soft adjacent trail." },
  { id: "dotm-circular-2", label: "Tri Orbit", description: "Three luminous heads orbit the circular ring at equal offsets, creating a triad chase that never overlaps into the old snake rhythm." },
  { id: "dotm-circular-3", label: "Plasma Veil", description: "A plasma-like diagonal sweep and pulsing core weave through the circular mask for a distinctly different motion signature." },
  { id: "dotm-circular-4", label: "Radar Arc", description: "A rotating radar arm scans the circular grid with a bright beam front, soft wake, and faint perimeter ring echo." },
  { id: "dotm-circular-5", label: "Nova Wheel", description: "Four rotating pinwheel blades spin through the circular matrix with a glowing center and soft trailing halo." },
  { id: "dotm-circular-6", label: "Phase Orb", description: "An off-center orbiting energy point traces a phase-shifted loop, creating a drifting orbital glow inside the circular matrix." },
  { id: "dotm-circular-7", label: "Gate Shift", description: "A scanning gate flips between vertical and horizontal sweeps, producing a crisp alternating shutter rhythm in the circular grid." },
  { id: "dotm-circular-8", label: "Heart Pulse", description: "Pulse bursts from the center with a dual-beat cadence, sending soft concentric pressure waves across the circular matrix." },
  { id: "dotm-circular-9", label: "Star Compass", description: "A cardinal beacon pattern: N/E/S/W sectors pulse in sequence with a dim opposite echo, creating a clear directional rhythm in the circular mask." },
  { id: "dotm-circular-10", label: "Binary Bloom", description: "Binary-style opacity tiers pulse in modular steps so only a few cells peak at once while others stay low, producing a crisp coded bloom." },
  { id: "dotm-circular-11", label: "Lunar Breathe", description: "A rotating crescent moon silhouette: bright lunar body, soft rim, and faint directional halo moving around the circular mask." },
  { id: "dotm-circular-12", label: "Arc Beacon", description: "A stepped 8-direction beacon beam sweeps around the circle with a dim opposite echo and diagonal spoke accents." },
  { id: "dotm-circular-13", label: "Twin Helix", description: "A circular-masked twin-helix: mirrored side strands weave inward and outward with intermittent interior bridge pulses." },
  { id: "dotm-circular-14", label: "Rung Shift", description: "A shifting DNA ladder where a bright horizontal rung steps row-by-row while side anchors sway and leave soft ghost echoes." },
  { id: "dotm-circular-15", label: "Glyph Cluster", description: "Braille-inspired grouped dot motifs cycle through rails, bridges, and cross forms inside the circular mask with crisp tiered opacity." },
  { id: "dotm-circular-16", label: "Rail Scan", description: "A braille rail scanline sweeps row-by-row between left and right cells, with near-column accents and soft trail falloff." },
  { id: "dotm-circular-17", label: "Checker Shift", description: "Braille-biased checker phases alternate in stepped shifts, keeping rails pronounced while the center cross supports readability." },
  { id: "dotm-circular-18", label: "Pulse Pair", description: "Mirrored braille dot pairs pulse from top and bottom toward the center, with a connective center-column accent." },
  { id: "dotm-circular-19", label: "Orbit Cell", description: "A bright braille cell head orbits the inner ring with a dim tail while rail columns remain softly active." },
  { id: "dotm-circular-20", label: "Glyph Cycle", description: "Distinct braille-like glyphs cycle in sequence with previous-frame ghosting for a crisp readable symbol transition." },
  { id: "dotm-triangle-1", label: "Core Spokes", description: "A triangle-masked matrix where three spoke lines originate at the center and travel outward to each triangle edge." },
  { id: "dotm-triangle-2", label: "Altitude Wave", description: "A soft altitude wave travels between apex and base while the center column remains gently present for shape readability." },
  { id: "dotm-triangle-3", label: "Corner Bounce", description: "A single head bounces between triangle corners along the perimeter path with a short fading tail." },
  { id: "dotm-triangle-4", label: "Vertex Chase", description: "Three staggered heads chase around the triangle perimeter, leaving short fading tails while all dots stay fixed in place." },
  { id: "dotm-triangle-5", label: "Row Sweep", description: "A reflected scanline sweeps from apex to base and back, animating only opacity bands across triangle rows." },
  { id: "dotm-triangle-6", label: "Braille Beat", description: "Triangle-masked braille dots fill down the left rail, then the right, then blink full and empty." },
  { id: "dotm-triangle-7", label: "Oblique Weave", description: "Diagonal harmonics keyed on row + col: bright bands glide along oblique lines through the triangle with a subtle second harmonic for texture." },
  { id: "dotm-triangle-8", label: "Wing Metronome", description: "The lower triangle splits into left and right wings that trade emphasis on a pendulum beat; apex and center pulse brightest when both sides meet in the middle." },
  { id: "dotm-triangle-9", label: "Corona Tier", description: "Eight-connected distance rings from the heart cell: a bright corona sweeps outward through discrete tiers then back, so depth reads as concentric energy shells." },
  { id: "dotm-triangle-10", label: "Column Rake", description: "A stepped head and tail snake the mask in strict column order (bottom to top per column, columns left to right), unlike perimeter chases or diagonal waves." },
  { id: "dotm-triangle-11", label: "Shelf Descent", description: "Cosine bands keyed on Manhattan distance from the apex (not the center): energy reads as horizontal tiers dropping through the triangle." },
  { id: "dotm-triangle-12", label: "Skew Drift", description: "Traveling harmonics on `row - col` so bright ridges move along NE\u2013SW obliques, orthogonal in feel to diagonal loaders that use `row + col`." },
  { id: "dotm-triangle-13", label: "Serpent Zip", description: "A stepped snake follows row-wise serpentine order (base left\u2192right, then alternating row directions) with a long tail \u2014 zigzag motion, not a column path." },
  { id: "dotm-triangle-14", label: "Pillar Sweep", description: "A smooth vertical beam sweeps grid columns 0\u21926; only triangle-masked dots respond so the silhouette lights one vertical slice at a time." },
  { id: "dotm-triangle-15", label: "Tripod Handoff", description: "Brightness hands off smoothly among the three silhouette vertices (apex, left base, right base) with Manhattan falloff \u2014 a corner-to-corner orbit, not a mod-3 lattice." },
  { id: "dotm-triangle-16", label: "Updraft", description: "A V-shaped thermal ridge moves through row-and-column space: brightness peaks along an inverted V so the front climbs the two lower flanks toward the apex, not a flat horizontal row scan like Row Sweep." },
  { id: "dotm-triangle-17", label: "Infinity Trace", description: "A stepped head and tail follow a single 10-cell path: left base up to the apex, down the right rim, then through (4,4) \u2192 center \u2192 (4,2) for a crossing loop." },
  { id: "dotm-triangle-18", label: "Hollow Shell", description: "The heart cell stays locked dim while every other triangle dot breathes together in phase \u2014 a hollow, ring-like pulse." },
  { id: "dotm-triangle-19", label: "Pivot Ray", description: "A Gaussian wedge of brightness rotates around the heart cell using each dot\u2019s polar angle \u2014 a clear pivoting searchlight, not a cosine-product moir\u00e9 field." },
  { id: "dotm-triangle-20", label: "Twin Perimeter", description: "Two stepped heads chase the outer perimeter path half a lap apart, each with its own tail; the heart cell stays quietly dim off the loop." },
  { id: "dotm-hex-1", label: "Hex Orbit", description: "A 3-4-5-4-3 hexagonal dot field with two soft perimeter heads chasing around the shell while the center stays quietly lit." },
  { id: "dotm-hex-2", label: "Prism Bloom", description: "Three rotating spokes sweep through the hex field with a soft outer shell pulse and a breathing center point." },
  { id: "dotm-hex-3", label: "Honey Gate", description: "Two diagonal bands slide through the honeycomb from opposite sides, meeting in a bright center flash before opening again." },
  { id: "dotm-hex-4", label: "Vertex Relay", description: "A bright signal hands off around the hex vertices while inner echo dots answer each corner and the center keeps a quick pulse." },
  { id: "dotm-hex-5", label: "Spiral Lattice", description: "Counter-rotating spiral waves cross through the hex lattice, creating a fast core pulse and softer outer wake." },
  { id: "dotm-hex-6", label: "Chevron March", description: "Smooth chevron bands flow through the hex field in a wrapped loop, keeping an obvious arrow pattern without a reset snap." },
  { id: "dotm-hex-7", label: "Hourglass Flip", description: "Top and bottom bars squeeze into a bright center hourglass, then flip into side rails and a diamond." },
  { id: "dotm-hex-8", label: "Glyph Flip", description: "Crisp symbolic masks flip between stars, chevrons, and rails for a snappy pixel-glyph loader." },
  { id: "dotm-hex-9", label: "Petal Shimmer", description: "A four-petal highlight rotates through the hex with a soft shell sheen and steady center glow." },
  { id: "dotm-hex-10", label: "Liquid Vortex", description: "Refined swirl bands and a slower lens highlight create a smoother liquid shimmer through the hex lattice." },
] as const;

export type DotmatrixRegistryId = (typeof DOTMATRIX_REGISTRY_MANIFEST)[number]["id"];