/**
 * Mock for @tabler/icons-svelte to avoid ESM resolution issues in Bun test.
 * The package has internal ./icons-list imports that fail under Bun's module resolver.
 * mock.module() must run before any import of @tabler/icons-svelte (hence preload).
 */
import { mock } from "bun:test";

const mockIcon = () => null;

mock.module("@tabler/icons-svelte", () => ({
	default: mockIcon,
	IconPlus: mockIcon,
	IconArrowRight: mockIcon,
	IconCheck: mockIcon,
	IconMessage: mockIcon,
	IconFile: mockIcon,
	IconChevronRight: mockIcon,
	IconChevronLeft: mockIcon,
	IconX: mockIcon,
	IconTerminal: mockIcon,
	IconTerminal2: mockIcon,
	IconCircleCheck: mockIcon,
	IconCircle: mockIcon,
	IconCircleX: mockIcon,
	IconCircleCheckFilled: mockIcon,
	IconSquare: mockIcon,
	IconDots: mockIcon,
	IconHelpCircle: mockIcon,
	IconAlertCircle: mockIcon,
	IconRefresh: mockIcon,
	IconDotsVertical: mockIcon,
	IconTrash: mockIcon,
	IconFolder: mockIcon,
	IconSend: mockIcon,
	IconMaximize: mockIcon,
	IconDownload: mockIcon,
	IconCode: mockIcon,
	IconEye: mockIcon,
	IconStar: mockIcon,
	IconAdjustments: mockIcon,
	IconLayoutSidebar: mockIcon,
	IconDatabase: mockIcon,
	IconSettings: mockIcon,
	IconClipboardList: mockIcon,
	IconAlignJustified: mockIcon,
	IconColumns: mockIcon,
	IconMoon: mockIcon,
	IconSun: mockIcon,
	IconListTree: mockIcon,
	IconTable: mockIcon,
	IconSparkles: mockIcon,
	IconAlertTriangle: mockIcon,
	IconKeyboard: mockIcon,
	IconLanguage: mockIcon,
	IconPencil: mockIcon,
	IconSearch: mockIcon,
	IconRotateClockwise: mockIcon,
	IconBrandGoogle: mockIcon,
	IconArrowLeft: mockIcon,
	IconGitBranch: mockIcon,
	IconExternalLink: mockIcon,
	IconPackage: mockIcon,
	IconEyeOff: mockIcon,
}));
