// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type AvailableModel = { modelId: string; name: string; description?: string | null }

export type AvailableMode = { id: string; name: string; description?: string | null }

/**
 * Command input hint.
 */
export type CommandInput = { 
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Pre-computed model info for display. Frontend uses this directly.
 */
export type DisplayableModel = { modelId: string; displayName: string; description?: string | null }

/**
 * Generic group of models. Label can be provider, base model name, or empty.
 */
export type DisplayModelGroup = { label: string; models: DisplayableModel[] }

/**
 * Display-ready model structure. Single representation—flat = one group.
 */
export type ModelsForDisplay = { groups: DisplayModelGroup[] }

export type SessionModelState = { availableModels?: AvailableModel[]; currentModelId?: string; modelsDisplay?: ModelsForDisplay }

export type SessionModes = { currentModeId?: string; availableModes?: AvailableMode[] }

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[] }

export type NewSessionResponse = { sessionId: string; models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

export type ResumeSessionResponse = { models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

