// This file was generated by specta. Do not edit this file manually.

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type AvailableModel = { modelId: string; name: string; description?: string | null }

export type ModeIconKind = "agent" | "plan" | "autonomous" | "bypass" | "ask" | "edit" | "review" | "unknown"

export type AvailableMode = { id: string; name: string; description?: string | null; iconKind?: ModeIconKind }

/**
 * Command input hint.
 */
export type CommandInput = {
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Pre-computed model info for display. Frontend uses this directly.
 */
export type DisplayableModel = { modelId: string; displayName: string; description?: string | null }

/**
 * Generic group of models. Label can be provider, base model name, or empty.
 */
export type DisplayModelGroup = { label: string; models: DisplayableModel[] }

export type ModelDisplayFamily = "claudeLike" | "codexReasoningEffort" | "providerGrouped"

export type UsageMetricsPresentation = "contextWindowOnly" | "spendAndContext"

export type ModelPresentationMetadata = { displayFamily: ModelDisplayFamily; usageMetrics: UsageMetricsPresentation; provider?: ProviderMetadataProjection }

/**
 * Display-ready model structure. Single representation—flat = one group.
 */
export type ModelsForDisplay = { groups: DisplayModelGroup[]; presentation?: ModelPresentationMetadata }

export type SessionModelState = { availableModels?: AvailableModel[]; currentModelId?: string | null; modelsDisplay?: ModelsForDisplay }

export type SessionModes = { currentModeId?: string; availableModes?: AvailableMode[] }

export type ResolvedCapabilityStatus = "resolved" | "partial" | "unsupported" | "failed"

export type ResolvedCapabilities = { status: ResolvedCapabilityStatus; availableModels: AvailableModel[]; currentModelId: string | null; modelsDisplay: ModelsForDisplay; providerMetadata: FrontendProviderProjection; availableModes: AvailableMode[]; currentModeId: string | null }

export type ConfigOptionPresentation = "hidden" | "advanced" | "compactReasoning" | "compactSpeed"

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[]; presentation?: ConfigOptionPresentation }

export type NewSessionResponse = { sessionId: string; creationAttemptId?: string | null; deferredCreation?: boolean; sequenceId?: number | null; sessionOpen?: SessionOpenResult | null; models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

export type ResumeSessionResponse = { models?: SessionModelState; modes?: SessionModes; availableCommands?: AvailableCommand[]; configOptions?: ConfigOptionData[] }

/**
 * Canonical agent identifier enum.
 *
 * This enum represents all valid agent types in the system.
 * Parsers set the enum directly based on their context (no normalization needed).
 */
export type CanonicalAgentId = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "forge" |
/**
 * Custom agent registered by user
 */
{ custom: string }

/**
 * Tool kind for routing to appropriate UI components.
 */
export type ToolKind = "read" | "read_lints" | "edit" | "execute" | "shell_input" | "search" | "glob" | "fetch" | "web_search" | "think" | "todo" | "question" | "task" | "task_output" | "skill" | "move" | "delete" | "enter_plan_mode" | "exit_plan_mode" | "create_plan" | "tool_search" | "browser" | "sql" | "unclassified" | "other"

/**
 * Tool call status.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed"

export type ChunkAggregationHint = "boundaryCarryover"

/**
 * A single file edit entry within an Edit tool call.
 *
 * A single `Edit` tool call may touch multiple files (e.g., OpenCode's `patch` tool
 * or Codex's multi-entry `changes` map). Each entry represents one file's change.
 */
export type EditEntry = {
/**
 * Path of the file being edited.
 */
filePath?: string | null;
/**
 * Original path when the edit entry represents a rename/move inside a multi-file edit patch.
 */
moveFrom?: string | null;
/**
 * Text being replaced (None = new file or full-file write).
 */
oldString?: string | null;
/**
 * Replacement text (standard edit).
 */
newString?: string | null;
/**
 * Full file content (create/overwrite variant).
 */
content?: string | null }

/**
 * Optional line range within a source file (read/search excerpts).
 */
export type ToolSourceRange = { startLine?: number | null; endLine?: number | null }

/**
 * Structured provider-supplied read context (path excerpts, ranges, metadata).
 *
 * Kept separate from [`ToolCallLocation`] (session routing) so read tools can carry
 * rich source metadata without overloading generic location lists (R13).
 */
export type ToolSourceContext = { path?: string | null; viewRange?: ToolSourceRange | null;
/**
 * Line-numbered or plain excerpt text from the provider (not synthesized UI copy).
 */
excerpt?: string | null }

/**
 * Tool arguments discriminated by tool kind.
 * Each variant contains exactly the fields needed for that tool type.
 */
export type ToolArguments = { kind: "read"; file_path?: string | null; source_context?: ToolSourceContext | null } | { kind: "readLints"; raw: JsonValue } |
/**
 * Edit tool arguments.
 *
 * `edits` is always a non-empty Vec. Single-file edits have exactly one entry;
 * multi-file edits (OpenCode `patch`, Codex multi-entry `changes` map) have N entries.
 */
{ kind: "edit"; edits: EditEntry[] } | { kind: "execute"; command?: string | null } | { kind: "shellInput"; shell_id?: string | null; input?: string | null } | { kind: "search"; query?: string | null; file_path?: string | null } | { kind: "glob"; pattern?: string | null; path?: string | null } | { kind: "fetch"; url?: string | null } | { kind: "webSearch"; query?: string | null } | { kind: "think"; description?: string | null; prompt?: string | null; subagent_type?: string | null; skill?: string | null; skill_args?: string | null; raw?: JsonValue | null } | { kind: "taskOutput"; task_id?: string | null; timeout?: number | null } | { kind: "move"; from?: string | null; to?: string | null } | { kind: "delete"; file_path?: string | null; file_paths?: string[] | null } | { kind: "planMode"; mode?: string | null; plan?: string | null; plan_file_path?: string | null; title?: string | null } | { kind: "toolSearch"; query?: string | null; max_results?: number | null } | { kind: "browser"; raw: JsonValue; action?: string | null; selector?: string | null; script?: string | null } | { kind: "sql"; query?: string | null; description?: string | null } | { kind: "unclassified"; provider_name: string; provider_kind_hint?: string | null; title?: string | null; arguments_preview?: string | null; signals_tried: string[] } | { kind: "other"; raw: JsonValue; intent?: string | null }

/**
 * Tool reference for permission/question requests.
 */
export type ToolReference = { messageId?: string | null; callId: string }

/**
 * Question option.
 */
export type QuestionOption = { label: string; description: string }

/**
 * Question item.
 */
export type QuestionItem = { question: string; header: string; options: QuestionOption[]; multiSelect: boolean }

/**
 * Explicit reply routing metadata for a canonical interaction.
 */
export type InteractionReplyHandlerKind = "json_rpc" | "http"

/**
 * Backend-owned reply handler metadata for interaction replies.
 */
export type InteractionReplyHandler = { kind: InteractionReplyHandlerKind; requestId: string }

/**
 * Permission request data.
 */
export type PermissionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; permission: string; patterns: string[]; metadata: JsonValue; always: string[]; autoAccepted: boolean; tool?: ToolReference | null }

/**
 * Question request data.
 */
export type QuestionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; questions: QuestionItem[]; tool?: ToolReference | null }

/**
 * Payload for usage telemetry session update (generic, not provider-specific).
 */
export type UsageTelemetryData = { sessionId: string; eventId?: string | null;
/**
 * Scope of the telemetry (e.g. "step", later "turn").
 */
scope?: string; costUsd?: number | null; tokens?: UsageTelemetryTokens; sourceModelId?: string | null; timestampMs?: number | null;
/**
 * Context window size reported by the agent (e.g. from usage_update `size` field).
 */
contextWindowSize?: number | null }

/**
 * Token counts for usage telemetry (generic, adapter-agnostic).
 */
export type UsageTelemetryTokens = { total?: number | null; input?: number | null; output?: number | null; cacheRead?: number | null; cacheWrite?: number | null; reasoning?: number | null }

/**
 * Plan step status.
 */
export type PlanStepStatus = "pending" | "in_progress" | "completed" | "failed"

/**
 * A single step in a plan.
 */
export type PlanStep = { description: string; status: PlanStepStatus }

/**
 * Plan signal source.
 */
export type PlanSource = "deterministic" | "heuristic"

/**
 * Confidence level for a plan signal.
 */
export type PlanConfidence = "high" | "medium"

/**
 * Plan data with steps and optional current step index.
 * Also supports streaming plan content from Edit tool writes.
 */
export type PlanData = { steps: PlanStep[]; currentStep?: number | null;
/**
 * Whether this payload currently represents an active plan.
 */
hasPlan?: boolean;
/**
 * Whether the plan content is still streaming (true) or complete (false).
 */
streaming?: boolean;
/**
 * The raw markdown content of the plan file (partial during streaming).
 */
content?: string | null;
/**
 * Normalized markdown content consumed by the frontend.
 */
contentMarkdown?: string | null;
/**
 * The file path where the plan is being written.
 */
filePath?: string | null;
/**
 * The plan title extracted from the first # heading.
 */
title?: string | null;
/**
 * Source quality of the signal.
 */
source?: PlanSource | null;
/**
 * Confidence of the signal.
 */
confidence?: PlanConfidence | null;
/**
 * Agent identifier that produced this plan.
 */
agentId?: string | null;
/**
 * Last update timestamp in milliseconds.
 */
updatedAt?: number | null }

/**
 * Todo item status.
 */
export type TodoStatus = "pending" | "in_progress" | "completed" | "cancelled"

/**
 * Todo item.
 */
export type TodoItem = { content: string; activeForm: string; status: TodoStatus; startedAt?: number | null; completedAt?: number | null; duration?: number | null }

/**
 * Semantic todo update operation derived from provider tool calls.
 */
export type TodoUpdateOperation = "replace" | "upsert" | "set_status" | "set_status_by_filter"

/**
 * Canonical todo update payload, independent from provider transport details.
 */
export type TodoUpdate = { operation: TodoUpdateOperation; items?: TodoItem[] | null; fromStatuses?: TodoStatus[] | null; toStatus?: TodoStatus | null }

export type TranscriptEntryRole = "user" | "assistant" | "tool" | "error"

export type TranscriptSegment = { kind: "text"; segmentId: string; text: string } | { kind: "thought"; segmentId: string; text: string }

export type TranscriptEntry = { entryId: string; role: TranscriptEntryRole; segments: TranscriptSegment[]; attemptId?: string | null; timestampMs?: number | null }

export type TranscriptSnapshot = { revision: number; entries: TranscriptEntry[] }

export type TranscriptDeltaOperation = { kind: "appendEntry"; entry: TranscriptEntry } | { kind: "appendSegment"; entryId: string; role: TranscriptEntryRole; segment: TranscriptSegment } | { kind: "replaceSnapshot"; snapshot: TranscriptSnapshot }

export type TranscriptDelta = { eventSeq: number; sessionId: string; snapshotRevision: number; operations: TranscriptDeltaOperation[] }

/**
 * Marker enum identifying the domain event kind.
 *
 * Kept as a flat string enum for backward-compatible discrimination
 * in frontend subscribers (`event.kind === "..."` comparisons).
 * Typed payload data is carried in [`SessionDomainEvent::payload`].
 */
export type SessionDomainEventKind = "session_identity_resolved" | "session_connected" | "session_disconnected" | "session_config_changed" | "turn_started" | "turn_completed" | "turn_failed" | "turn_cancelled" | "user_message_segment_appended" | "assistant_message_segment_appended" | "assistant_thought_segment_appended" | "operation_upserted" | "operation_child_linked" | "operation_status_updated" | "operation_completed" | "interaction_upserted" | "interaction_resolved" | "interaction_cancelled" | "usage_telemetry_updated" | "todo_state_updated"

/**
 * Typed payload carried by a canonical domain event.
 *
 * Each variant corresponds to a [`SessionDomainEventKind`] and carries the
 * structured data that downstream reducers and projections need.  Consumers
 * can switch on `event.kind` for quick discrimination and access the typed
 * payload via `event.payload` when richer data is required.
 */
export type SessionDomainEventPayload = { kind: "session_identity_resolved"; resolved_provider_session_id: string } | { kind: "session_connected" } | { kind: "session_disconnected" } | { kind: "session_config_changed" } | { kind: "turn_started"; turn_id: string } | { kind: "turn_completed"; turn_id: string | null } | { kind: "turn_failed"; turn_id: string | null; error_message: string } | { kind: "turn_cancelled"; turn_id: string | null } | { kind: "user_message_segment_appended"; message_id: string | null; part_id: string | null; text: string } | { kind: "assistant_message_segment_appended"; message_id: string | null; part_id: string | null; text: string } | { kind: "assistant_thought_segment_appended"; message_id: string | null; part_id: string | null; text: string } | { kind: "operation_upserted"; operation_id: string; tool_call_id: string; tool_name: string; tool_kind: ToolKind; status: ToolCallStatus; parent_operation_id: string | null } | { kind: "operation_child_linked"; parent_operation_id: string; child_operation_id: string } | { kind: "operation_status_updated"; operation_id: string; tool_call_id: string; status: ToolCallStatus } | { kind: "operation_completed"; operation_id: string; tool_call_id: string; status: ToolCallStatus } | { kind: "interaction_upserted"; interaction_id: string; interaction_kind: InteractionKind } | { kind: "interaction_resolved"; interaction_id: string } | { kind: "interaction_cancelled"; interaction_id: string } | { kind: "usage_telemetry_updated"; data: UsageTelemetryData } | { kind: "todo_state_updated"; update: TodoUpdate }

/**
 * Canonical domain event envelope.
 *
 * `kind` identifies the event type for quick string-based discrimination.
 * `payload` carries typed structured data — `None` only for events where
 * payloads are not yet wired at the emission site.
 */
export type SessionDomainEvent = { event_id: string; seq: number; session_id: string; provider_session_id: string | null; occurred_at_ms: number; causation_id: string | null; kind: SessionDomainEventKind; payload?: SessionDomainEventPayload | null }

/**
 * Tool call location.
 */
export type ToolCallLocation = { path: string }

/**
 * Skill metadata for skill tool calls.
 */
export type SkillMeta = { description?: string | null; filePath?: string | null }

/**
 * Answered question data from toolUseResult field in JSONL.
 * Stores both the questions and the user's answers.
 */
export type QuestionAnswer = {
/**
 * The questions that were asked
 */
questions: QuestionItem[];
/**
 * Map of question text to answer(s) - value is string for single-select, array for multi-select
 */
answers: Partial<{ [key in string]: JsonValue }> }

export type SessionTurnState = "Idle" | "Running" | "Completed" | "Failed" | "Cancelled"

export type SessionSnapshot = { session_id: string; agent_id: CanonicalAgentId | null; last_event_seq: number; turn_state: SessionTurnState; message_count: number; active_tool_call_ids: string[]; completed_tool_call_ids: string[]; active_turn_failure?: TurnFailureSnapshot | null; last_terminal_turn_id?: string | null }

export type OperationState = "pending" | "running" | "blocked" | "completed" | "failed" | "cancelled" | "degraded"

export type OperationDegradationCode = "impossible_transition" | "missing_evidence" | "absent_from_history" | "classification_failure" | "invalid_provenance_key"

export type OperationDegradationReason = { code: OperationDegradationCode; detail?: string | null }

export type OperationSourceLink = { kind: "transcript_linked"; entry_id: string } | { kind: "synthetic"; reason: string } | { kind: "degraded"; reason: OperationDegradationReason }

export type OperationSnapshot = { id: string; session_id: string; tool_call_id: string; name: string; kind: ToolKind | null;
/**
 * Provider-layer provenance status. Use `operation_state` for canonical state decisions.
 */
provider_status: ToolCallStatus; title: string | null; arguments: ToolArguments; progressive_arguments: ToolArguments | null; result: JsonValue | null; command: string | null; normalized_todos: TodoItem[] | null; parent_tool_call_id: string | null; parent_operation_id: string | null; child_tool_call_ids: string[]; child_operation_ids: string[]; operation_provenance_key?: string | null; operation_state: OperationState; locations?: ToolCallLocation[] | null; skill_meta?: SkillMeta | null; normalized_questions?: QuestionItem[] | null; question_answer?: QuestionAnswer | null; awaiting_plan_approval: boolean; plan_approval_request_id?: number | null; started_at_ms?: number | null; completed_at_ms?: number | null; source_link: OperationSourceLink; degradation_reason?: OperationDegradationReason | null }

export type InteractionKind = "Permission" | "Question" | "PlanApproval"

export type InteractionState = "Pending" | "Approved" | "Rejected" | "Answered" | "Unresolved"

export type PlanApprovalSource = "CreatePlan" | "ExitPlanMode"

export type InteractionPayload = { Permission: PermissionData } | { Question: QuestionData } | { PlanApproval: { source: PlanApprovalSource } }

export type InteractionResponse = { kind: "permission"; accepted: boolean; option_id?: string | null; reply?: string | null } | { kind: "question"; answers: JsonValue } | { kind: "plan_approval"; approved: boolean }

export type InteractionSnapshot = { id: string; session_id: string; kind: InteractionKind; state: InteractionState; json_rpc_request_id: number | null; reply_handler: InteractionReplyHandler | null; tool_reference: ToolReference | null; responded_at_event_seq: number | null; response: InteractionResponse | null; payload: InteractionPayload; canonical_operation_id?: string | null }

/**
 * Turn error severity.
 */
export type TurnErrorKind = "recoverable" | "fatal"

/**
 * Turn error source.
 */
export type TurnErrorSource = "json_rpc" | "transport" | "process" | "unknown"

export type TurnFailureSnapshot = { turn_id: string | null; message: string; code?: string | null; kind: TurnErrorKind; source: TurnErrorSource }

export type LifecycleStatus = "reserved" | "activating" | "ready" | "reconnecting" | "detached" | "failed" | "archived"

export type DetachedReason = "restoredRequiresAttach" | "reconnectExhausted" | "abandonedInFlight" | "legacyAmbiguousRestore" | "closedByClient"

export type FailureReason = "deterministicRestoreFault" | "activationFailed" | "resumeFailed" | "sessionGoneUpstream" | "providerSessionMismatch" | "corruptedPersistedState" | "explicitErrorHandlingRequired" | "legacyIrrecoverable"

export type LifecycleState = { status: LifecycleStatus; detachedReason?: DetachedReason | null; failureReason?: FailureReason | null; errorMessage?: string | null }

export type LifecycleCheckpoint = {
/**
 * Older persisted checkpoints may omit this field; treat as current version for migration.
 */
schemaVersion?: number; graphRevision: number; lifecycle: LifecycleState; capabilities: SessionGraphCapabilities }

export type SessionProjectionSnapshot = { session: SessionSnapshot | null; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; runtime?: LifecycleCheckpoint | null }

/**
 * Payload for the `error` outcome — persisted state was found but could not
 * be loaded or proven consistent.
 */
export type SessionOpenErrorReason = "parseFailure" | "providerUnavailable" | "providerHistoryMissing" | "providerUnparseable" | "providerValidationFailed" | "staleLineageRecovery" | "internal"

/**
 * Payload for the `error` outcome — persisted state was found but could not
 * be loaded or proven consistent.
 */
export type SessionOpenError = { requestedSessionId: string; message: string; reason: SessionOpenErrorReason; retryable: boolean }

/**
 * Full payload for a `found` outcome.
 */
export type SessionOpenFound = {
/**
 * The ID supplied by the caller (may be a provider-side alias).
 */
requestedSessionId: string;
/**
 * The Acepe-local canonical session identifier.
 */
canonicalSessionId: string;
/**
 * `true` when `requested_session_id` differs from `canonical_session_id`
 * (i.e. the caller supplied a provider-side alias that was resolved to a
 * different canonical ID).
 */
isAlias: boolean;
/**
 * Proven journal cutoff.  `0` only when no journal events exist yet.
 */
lastEventSeq: number;
/**
 * Canonical graph frontier at the proven cutoff.
 *
 * During the compatibility window this may still be seeded from persisted
 * state that mirrors `last_event_seq`, but open/materialization paths must
 * carry it explicitly instead of re-deriving graph lineage from delivery.
 */
graphRevision: number;
/**
 * Single-use attach token (UUID string).  All hub events for this session
 * published after this token is armed are buffered in the `event_hub`
 * reservation until the token is claimed (Unit 3) or expires after 30 s
 * of inactivity.
 */
openToken: string; agentId: CanonicalAgentId; projectPath: string; worktreePath: string | null; sourcePath: string | null; sequenceId?: number | null; transcriptSnapshot: TranscriptSnapshot; sessionTitle: string; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; turnState: SessionTurnState; messageCount: number; activity: SessionGraphActivity; activeStreamingTail: ActiveStreamingTail | null; lifecycle: SessionGraphLifecycle; capabilities: SessionGraphCapabilities; activeTurnFailure?: TurnFailureSnapshot | null; lastTerminalTurnId?: string | null }

/**
 * Payload for the `missing` outcome — no persisted content was found for the
 * requested session identifier.
 */
export type SessionOpenMissing = { requestedSessionId: string }

/**
 * The unified outcome of a session-open request.
 *
 * Returned by every session entry point (new, resume, history open).  The
 * frontend MUST NOT fetch projection state separately after receiving a
 * `Found` result; everything needed before live connect begins is included.
 */
export type SessionOpenResult =
/**
 * Session was found; all pre-connect state is fully populated.
 *
 * `Box`ed to keep the enum size bounded — `SessionOpenFound` carries
 * the full projection snapshot, which is significantly larger than the
 * `Missing` and `Error` payloads.
 */
({ outcome: "found" } & SessionOpenFound) | ({ outcome: "missing" } & SessionOpenMissing) | ({ outcome: "error" } & SessionOpenError)

export type SessionGraphRevision = { graphRevision: number; transcriptRevision: number; lastEventSeq: number }

export type SessionRecommendedAction = "none" | "wait" | "send" | "resume" | "retry" | "archive"

export type SessionRecoveryPhase = "none" | "activating" | "reconnecting" | "detached" | "failed" | "archived"

export type SessionGraphActionability = { canSend: boolean; canResume: boolean; canRetry: boolean; canArchive: boolean; canConfigure: boolean; recommendedAction: SessionRecommendedAction; recoveryPhase: SessionRecoveryPhase; compactStatus: LifecycleStatus }

export type SessionGraphLifecycle = { status: LifecycleStatus; detachedReason?: DetachedReason | null; failureReason?: FailureReason | null; errorMessage?: string | null; actionability: SessionGraphActionability }

export type SessionGraphCapabilities = { models?: SessionModelState | null; modes?: SessionModes | null; availableCommands?: AvailableCommand[] | null; configOptions?: ConfigOptionData[] | null; autonomousEnabled?: boolean | null }

export type CapabilityPreviewState = "canonical" | "pending" | "failed" | "partial" | "stale"

export type SessionGraphActivityKind = "awaiting_model" | "running_operation" | "waiting_for_user" | "paused" | "error" | "idle"

export type SessionGraphActivity = { kind: SessionGraphActivityKind; activeOperationCount: number; activeSubagentCount: number; dominantOperationId?: string | null; blockingInteractionId?: string | null }

export type ActiveStreamingTailContentKind = "thought" | "message"

export type ActiveStreamingTail = { rowId: string; contentKind: ActiveStreamingTailContentKind }

export type TranscriptViewportRowKind = "user" | "assistantText" | "assistantThought" | "tool" | "error"

export type TranscriptViewportOperationLink = { operationId: string; toolCallId: string; name: string; state: OperationState }

export type TranscriptViewportInteractionLink = { interactionId: string; kind: InteractionKind; state: InteractionState; operationId: string | null }

export type TranscriptViewportRowContent = { kind: "transcript"; role: TranscriptEntryRole; segments: TranscriptSegment[] }

export type TranscriptViewportRow = { rowId: string; sourceEntryId: string; kind: TranscriptViewportRowKind; version: string; anchorEligible: boolean; activeStreamingTail: ActiveStreamingTailContentKind | null; operationLinks: TranscriptViewportOperationLink[]; interactionLinks: TranscriptViewportInteractionLink[]; content: TranscriptViewportRowContent }

export type ViewportMode = { kind: "followingTail" } | { kind: "detached"; anchorRowId: string; offsetFromAnchorPx: number }

export type ViewportWindow = { offsetPx: number; totalHeightPx: number; visibleStartIndex: number; visibleEndIndex: number; mode: ViewportMode }

export type SessionStateGraph = { requestedSessionId: string; canonicalSessionId: string; isAlias: boolean; agentId: CanonicalAgentId; projectPath: string; worktreePath?: string | null; sourcePath?: string | null; sequenceId?: number | null; revision: SessionGraphRevision; transcriptSnapshot: TranscriptSnapshot; operations: OperationSnapshot[]; interactions: InteractionSnapshot[]; turnState: SessionTurnState; messageCount: number; activeStreamingTail: ActiveStreamingTail | null; activeTurnFailure?: TurnFailureSnapshot | null; lastTerminalTurnId?: string | null; lifecycle: SessionGraphLifecycle; activity: SessionGraphActivity; capabilities: SessionGraphCapabilities }

export type SessionStateSnapshotMaterialization = { graph: SessionStateGraph }

export type SessionStateDelta = { fromRevision: SessionGraphRevision; toRevision: SessionGraphRevision; activity: SessionGraphActivity; turnState: SessionTurnState; activeTurnFailure?: TurnFailureSnapshot | null; lastTerminalTurnId?: string | null; activeStreamingTail: ActiveStreamingTail | null; transcriptOperations: TranscriptDeltaOperation[]; operationPatches: OperationSnapshot[]; interactionPatches: InteractionSnapshot[]; changedFields?: string[] }

export type AssistantTextDeltaPayload = { turnId: string; rowId: string; charOffset: number; deltaText: string; producedAtMonotonicMs: number; revision: number }

/**
 * Diagnostic emitted alongside a buffer push/delta (e.g. a rejected height
 * confirmation or a shrunk buffer).
 */
export type ViewportBufferDiagnostic = { code: string; rowId: string | null }

/**
 * Full buffered slice of the canonical layout pushed to the WebView. The
 * WebView resolves in-buffer scroll offsets locally (no IPC per frame) and
 * only requests a refill when scrolling near/outside `[buffer_start_index,
 * buffer_end_index)`. `request_generation` echoes the generation of a refill
 * request so the store can reject stale command responses; live (unsolicited)
 * pushes carry `None`.
 */
export type ViewportBufferPush = { sessionId: string; graphRevision: SessionGraphRevision; viewportRevision: number;
/**
 * Per-session monotonic emission sequence (the total-order authority for
 * the buffer protocol). A push resets the consumer's sequence baseline to
 * this value; subsequent deltas must chain contiguously from it. Because
 * `viewport_revision` does NOT advance on streaming row appends, it cannot
 * sequence the two independent delivery channels (command-reply vs live
 * event stream); `emission_seq` can, turning any out-of-order arrival into
 * a detectable gap (→ fresh push) instead of silent buffer corruption.
 */
emissionSeq: number; bufferStartIndex: number; bufferEndIndex: number;
/**
 * Total number of rows in the full canonical layout. Lets the WebView tell
 * whether a buffer edge is also the layout extreme (so it must NOT request
 * a refill past it).
 */
layoutRowCount: number; totalHeightPx: number;
/**
 * Absolute pixel offset of the bottom of the last buffered row
 * (= `offset_at_index(buffer_end_index)`). Equals `total_height_px` only
 * when the buffer reaches the layout end. Lets the WebView compute the
 * buffered pixel span `[offsets_px[0], buffer_end_offset_px)` without
 * per-row heights.
 */
bufferEndOffsetPx: number; rows: TranscriptViewportRow[]; offsetsPx: number[]; mode: ViewportMode; requestGeneration?: number | null;
/**
 * Absolute scrollTop the WebView should adopt when this push repositions the
 * viewport (initial open, reveal, follow-tail). `None` for a pure refill or
 * an accepted-height-confirmation re-push in `Detached` mode, where the
 * user's current scrollTop is authoritative and only a *relative*
 * `scroll_anchor_correction_px` may be applied. Exactly one of
 * `scroll_top_target` (absolute) or `scroll_anchor_correction_px` (relative)
 * is ever set per emission — never both — to avoid double-applying a scroll
 * correction.
 */
scrollTopTarget?: number | null;
/**
 * Signed pixel correction the WebView adds to its *live* scrollTop to keep
 * the visible content pinned when canonical geometry above the viewport
 * shifted (a row above the viewport re-measured). Relative — never fights
 * the user's in-flight scroll position. `None` when nothing above the
 * viewport moved or when an absolute `scroll_top_target` is used instead.
 */
scrollAnchorCorrectionPx?: number | null; diagnostics: ViewportBufferDiagnostic[] }

/**
 * Incremental buffer mutation. Applies iff `emission_seq` chains contiguously
 * from the consumer's last applied sequence (`emission_seq == current + 1`);
 * an older `emission_seq` is a stale duplicate (dropped), a newer-than-next
 * one is a gap that forces a fresh `ViewportBufferPush`. `emission_seq` — not
 * `from_viewport_revision` — is the apply-ordering authority, because pure
 * streaming appends do not advance `viewport_revision`. The revision fields
 * remain for diagnostics and snapshot newer-wins on pushes. Exactly one of
 * `scroll_top_target` (absolute) or `scroll_anchor_correction_px` (relative)
 * should be set to avoid double-applying a scroll correction.
 */
export type ViewportBufferDelta = { sessionId: string; graphRevision: SessionGraphRevision;
/**
 * Per-session monotonic emission sequence; see [`ViewportBufferPush::emission_seq`].
 */
emissionSeq: number; fromViewportRevision: number; toViewportRevision: number; prependedRows: TranscriptViewportRow[]; prependedOffsetsPx: number[]; appendedRows: TranscriptViewportRow[]; appendedOffsetsPx: number[]; removedRowIds: string[];
/**
 * Total rows in the canonical layout after this delta. Lets the consumer
 * re-evaluate `needsRefill`'s "has content below" edge as streaming grows
 * the transcript, without a fresh push.
 */
layoutRowCount: number; totalHeightPx: number;
/**
 * Absolute pixel bottom of the last buffered row after this delta (top of
 * the row past `buffer_end_index`). Equals `total_height_px` only when the
 * buffer reaches the layout end. Required so the consumer can maintain the
 * bottom-edge refill math without per-row heights.
 */
bufferEndOffsetPx: number; scrollAnchorCorrectionPx?: number | null; scrollTopTarget?: number | null; diagnostics: ViewportBufferDiagnostic[] }

export type TranscriptViewportCommandRevision = { graphRevision: number; transcriptRevision: number; lastEventSeq: number }

export type SessionStatePayload = { kind: "snapshot"; graph: SessionStateGraph } | { kind: "delta"; delta: SessionStateDelta } | { kind: "lifecycle"; lifecycle: SessionGraphLifecycle; revision: SessionGraphRevision } | { kind: "capabilities"; capabilities: SessionGraphCapabilities; revision: SessionGraphRevision; pending_mutation_id?: string | null; preview_state: CapabilityPreviewState } | { kind: "telemetry"; telemetry: UsageTelemetryData; revision: SessionGraphRevision } | { kind: "plan"; plan: PlanData; revision: SessionGraphRevision } | { kind: "assistantTextDelta"; delta: AssistantTextDeltaPayload } | { kind: "viewportBufferPush"; push: ViewportBufferPush } | { kind: "viewportBufferDelta"; delta: ViewportBufferDelta }

export type SessionStateEnvelope = { sessionId: string; graphRevision: number; lastEventSeq: number; payload: SessionStatePayload }


export type ProviderBrand = "claude-code" | "copilot" | "cursor" | "opencode" | "codex" | "custom";

export type ProviderVariantGroup = "plain" | "reasoningEffort";

export type PreconnectionSlashMode = "startupGlobal" | "projectScoped" | "unsupported";

export type PreconnectionCapabilityMode = "startupGlobal" | "projectScoped" | "unsupported";

export type ImplicitSessionCreationMode = "allowed" | "explicitUserAction";

export type ProviderMetadataProjection = {
	providerBrand: ProviderBrand;
	displayName: string;
	displayOrder: number;
	supportsModelDefaults: boolean;
	variantGroup: ProviderVariantGroup;
	defaultAlias?: string;
	reasoningEffortSupport: boolean;
	preconnectionSlashMode: PreconnectionSlashMode;
	preconnectionCapabilityMode: PreconnectionCapabilityMode;
	implicitSessionCreationMode: ImplicitSessionCreationMode;
};

export type FrontendProviderProjection = ProviderMetadataProjection;

export type ModelsForDisplayWithProvider = ModelsForDisplay;

