// This file was generated by specta. Do not edit this file manually.

import type { DetachedReason, FailureReason, SessionModelState, SessionModes, TodoUpdate, TodoUpdateOperation } from "./acp-types.js";

// JsonValue represents any valid JSON value
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/**
 * Token counts for usage telemetry (generic, adapter-agnostic).
 */
export type UsageTelemetryTokens = { total?: number | null; input?: number | null; output?: number | null; cacheRead?: number | null; cacheWrite?: number | null; reasoning?: number | null }

export type ContextWindowSource = "provider-explicit" | "provider-model-capability" | "unknown"

/**
 * Payload for usage telemetry session update (generic, not provider-specific).
 */
export type UsageTelemetryData = { sessionId: string; eventId?: string | null;
/**
 * Scope of the telemetry (e.g. "step", later "turn").
 */
scope?: string; costUsd?: number | null; tokens?: UsageTelemetryTokens; sourceModelId?: string | null; timestampMs?: number | null;
/**
 * Context window size reported by the agent (e.g. from usage_update `size` field).
 */
contextWindowSize?: number | null; contextWindowSource?: ContextWindowSource | null;
/**
 * When set, this telemetry belongs to a spawned sub-agent rather than the
 * top-level session turn. The id is the parent `Task` tool-call id, used to
 * aggregate per-sub-agent usage downstream. `None` = session-level telemetry.
 */
parentToolUseId?: string | null }

export type SessionCompactionStatus = "preparing" | "completed" | "usage_reset" | "failed"

export type SessionCompactionTrigger = "auto" | "manual" | "unknown"

export type SessionCompactionEvent = { eventId: string; sessionId: string; status: SessionCompactionStatus; trigger: SessionCompactionTrigger; preCompactionTokens?: number | null; postCompactionTokens?: number | null; droppedTokens?: number | null; contextWindowSize?: number | null; durationMs?: number | null; precomputed?: boolean | null; preservedMessageCount?: number | null; cumulativeDroppedTokens?: number | null; timestampMs?: number | null; summary?: string | null; providerMetadata: JsonValue }

/**
 * Session update types from ACP protocol.
 *
 * These are notifications sent by the agent during a prompt response.
 * They represent streaming updates to the session state.
 *
 * Uses internally tagged representation with `type` field for clean TypeScript discrimination.
 * Example: `{ "type": "toolCall", "tool_call": {...}, "session_id": "..." }`
 */
export type SessionUpdate = { type: "userMessageChunk"; chunk: ContentChunk; sessionId?: string | null; attemptId?: string | null } | { type: "agentMessageChunk"; chunk: ContentChunk; part_id?: string | null; message_id?: string | null; parent_tool_use_id?: string | null; session_id?: string | null; produced_at_monotonic_ms?: number | null } | { type: "agentThoughtChunk"; chunk: ContentChunk; part_id?: string | null; message_id?: string | null; parent_tool_use_id?: string | null; session_id?: string | null } | { type: "toolCall"; tool_call: ToolCallData; session_id?: string | null } | { type: "toolCallUpdate"; update: ToolCallUpdateData; session_id?: string | null } | { type: "plan"; plan: PlanData; session_id?: string | null } | { type: "availableCommandsUpdate"; update: AvailableCommandsData; session_id?: string | null } | { type: "currentModeUpdate"; update: CurrentModeData; session_id?: string | null } | { type: "configOptionUpdate"; update: ConfigOptionUpdateData; session_id?: string | null } | { type: "permissionRequest"; permission: PermissionData; session_id?: string | null } | { type: "questionRequest"; question: QuestionData; session_id?: string | null } |
/**
 * Indicates that the current turn/prompt has completed.
 * This is emitted when the JSON-RPC response for a prompt request is received.
 */
{ type: "turnComplete"; session_id?: string | null; turn_id?: string | null } |
/**
 * Indicates that the current turn/prompt failed with an error.
 * This is emitted when the JSON-RPC response contains an error.
 */
{ type: "turnError"; error: TurnErrorData; session_id?: string | null; turn_id?: string | null } |
/**
 * Indicates that the current turn/prompt was cancelled by the user.
 * This is emitted after the provider accepts a cancel/interrupt request.
 */
{ type: "turnCancelled"; session_id?: string | null; turn_id?: string | null } |
/**
 * Usage/cost and token telemetry from the agent (adapter-agnostic).
 * Emitted by adapters (e.g. OpenCode step-finish) for spend and context UI.
 */
{ type: "usageTelemetryUpdate"; data: UsageTelemetryData } |
/**
 * Canonical session activity for provider-side context compaction.
 */
{ type: "compactionEvent"; event: SessionCompactionEvent; session_id?: string | null } |
/**
 * Emitted by the async resume task when session connection completes successfully.
 * Carries session capabilities so the frontend can update canonical projection.
 */
{ type: "connectionComplete"; session_id: string; attempt_id: number; models: SessionModelState; modes: SessionModes; available_commands?: AvailableCommand[] | null; config_options?: ConfigOptionData[] | null; autonomous_enabled?: boolean | null } |
/**
 * Emitted by the async resume task when session connection fails.
 *
 * `failure_reason` carries the canonical classification (e.g.
 * `SessionGoneUpstream` for upstream-permanent failures, `ResumeFailed`
 * for transient/transport faults). `error` carries the raw provider
 * text verbatim for log/debug surfaces; user-facing English copy is
 * composed downstream in TS from `(agentId, failure_reason)`.
 */
{ type: "connectionFailed"; session_id: string; attempt_id: number; error: string; failure_reason: FailureReason } |
/**
 * Emitted when a resume cannot proceed because of a recoverable
 * precondition (e.g. the agent requires an interactive sign-in). This is
 * intentionally NOT a `ConnectionFailed` event — the session is not in an
 * error state, just parked awaiting user action. The snapshot handler
 * routes it to `LifecycleState::detached(reason)`.
 */
{ type: "sessionDetached"; session_id: string; attempt_id: number; detached_reason: DetachedReason }

export type ChunkAggregationHint = "boundaryCarryover"

/**
 * ContentChunk represents a chunk of content being streamed.
 *
 * This handles both direct format `{ content: ContentBlock }`
 * and nested format `{ chunk: { content: ContentBlock } }`.
 */
export type ContentChunk = { content: ContentBlock; aggregationHint?: ChunkAggregationHint | null }

/**
 * Tool call data.
 */
export type ToolCallData = { id: string; name: string; arguments: ToolArguments; diagnosticRawInput?: JsonValue | null; status: ToolCallStatus; result?: JsonValue | null; kind?: ToolKind | null; title?: string | null; locations?: ToolCallLocation[] | null; skillMeta?: SkillMeta | null;
/**
 * Normalized questions extracted from question tool calls.
 * This provides a unified format for questions across all agents.
 */
normalizedQuestions?: QuestionItem[] | null;
/**
 * Normalized todos extracted from TodoWrite tool calls.
 * This provides a unified format for todos across all agents.
 */
normalizedTodos?: TodoItem[] | null;
/**
 * Semantic todo update derived from provider tool calls while preserving transport provenance.
 */
normalizedTodoUpdate?: TodoUpdate | null;
/**
 * Parent task ID for nested tool calls.
 */
parentToolUseId?: string | null;
/**
 * Child tool calls belonging to this task.
 */
taskChildren?: ToolCallData[] | null;
/**
 * Answered question data (questions + user's answers).
 * Present when this is a question tool call that has been answered.
 */
questionAnswer?: QuestionAnswer | null;
/**
 * Whether this tool call is awaiting plan approval from the user.
 * Set on `cursor/create_plan` tool calls; the user must approve or reject before the agent continues.
 */
awaitingPlanApproval: boolean;
/**
 * JSON-RPC request ID to use when responding to plan approval.
 * Present when `awaiting_plan_approval` is true.
 */
planApprovalRequestId?: number | null }

/**
 * A single file edit entry within an Edit tool call.
 *
 * A single `Edit` tool call may touch multiple files (e.g., OpenCode's `patch` tool
 * or Codex's multi-entry `changes` map). Each entry represents one file's change.
 */
export type EditEntry = {
/**
 * Path of the file being edited.
 */
filePath?: string | null;
/**
 * Original path when the edit entry represents a rename/move inside a multi-file edit patch.
 */
moveFrom?: string | null;
/**
 * Text being replaced (None = new file or full-file write).
 */
oldString?: string | null;
/**
 * Replacement text (standard edit).
 */
newString?: string | null;
/**
 * Full file content (create/overwrite variant).
 */
content?: string | null }

/**
 * Optional line range within a source file (read/search excerpts).
 */
export type ToolSourceRange = { startLine?: number | null; endLine?: number | null }

/**
 * Structured provider-supplied read context (path excerpts, ranges, metadata).
 *
 * Kept separate from [`ToolCallLocation`] (session routing) so read tools can carry
 * rich source metadata without overloading generic location lists (R13).
 */
export type ToolSourceContext = { path?: string | null; viewRange?: ToolSourceRange | null;
/**
 * Line-numbered or plain excerpt text from the provider (not synthesized UI copy).
 */
excerpt?: string | null }

/**
 * Tool arguments discriminated by tool kind.
 * Each variant contains exactly the fields needed for that tool type.
 */
export type ToolArguments = { kind: "read"; file_path?: string | null; source_context?: ToolSourceContext | null } | { kind: "readLints"; raw: JsonValue } |
/**
 * Edit tool arguments.
 *
 * `edits` is always a non-empty Vec. Single-file edits have exactly one entry;
 * multi-file edits (OpenCode `patch`, Codex multi-entry `changes` map) have N entries.
 */
{ kind: "edit"; edits: EditEntry[] } | { kind: "execute"; command?: string | null } | { kind: "shellInput"; shell_id?: string | null; input?: string | null } | { kind: "search"; query?: string | null; file_path?: string | null } | { kind: "glob"; pattern?: string | null; path?: string | null } | { kind: "fetch"; url?: string | null } | { kind: "webSearch"; query?: string | null } | { kind: "think"; description?: string | null; prompt?: string | null; subagent_type?: string | null; skill?: string | null; skill_args?: string | null; raw?: JsonValue | null } | { kind: "taskOutput"; task_id?: string | null; timeout?: number | null } | { kind: "move"; from?: string | null; to?: string | null } | { kind: "delete"; file_path?: string | null; file_paths?: string[] | null } | { kind: "planMode"; mode?: string | null; plan?: string | null; plan_file_path?: string | null; title?: string | null } | { kind: "toolSearch"; query?: string | null; max_results?: number | null } | { kind: "browser"; raw: JsonValue; action?: string | null; selector?: string | null; script?: string | null } | { kind: "computer"; verb?: string | null; target_id?: string | null; epoch?: string | null; text?: string | null; key?: string | null; delta_x?: number | null; delta_y?: number | null; include_bounds?: boolean | null; include_screenshot?: boolean | null } | { kind: "sql"; query?: string | null; description?: string | null } | { kind: "unclassified"; provider_name: string; provider_kind_hint?: string | null; title?: string | null; arguments_preview?: string | null; signals_tried: string[] } | { kind: "other"; raw: JsonValue; intent?: string | null }

/**
 * Tool call update data.
 */
export type ToolCallUpdateData = { toolCallId: string; status?: ToolCallStatus | null; result?: JsonValue | null; content?: ContentBlock[] | null; rawOutput?: JsonValue | null; title?: string | null; locations?: ToolCallLocation[] | null;
/**
 * Streaming input delta - partial JSON string for progressive tool input display.
 * Extracted from _meta.claudeCode.streamingInputDelta.
 */
streamingInputDelta?: string | null;
/**
 * Progressive normalized todos from streaming input.
 * Populated by the streaming accumulator for TodoWrite-like tools.
 */
normalizedTodos?: TodoItem[] | null;
/**
 * Progressive normalized questions from streaming input.
 * Populated by the streaming accumulator for AskUserQuestion-like tools.
 */
normalizedQuestions?: QuestionItem[] | null;
/**
 * Pre-parsed streaming arguments for progressive tool input display.
 * Produced by the streaming accumulator when partial JSON parse succeeds.
 */
streamingArguments?: ToolArguments | null;
/**
 * Typed tool arguments from rawInput in tool_call_update.
 * Upstream v0.18+ sends rawInput in the update, not the initial tool_call.
 */
arguments?: ToolArguments | null;
/**
 * Human-readable reason when status is `Failed`.
 * Distinguishes user-denied permissions ("Permission denied by user")
 * from actual runtime failures without changing the status enum.
 */
failureReason?: string | null }

/**
 * Plan data with steps and optional current step index.
 * Also supports streaming plan content from Edit tool writes.
 */
export type PlanData = { steps: PlanStep[]; currentStep?: number | null;
/**
 * Whether this payload currently represents an active plan.
 */
hasPlan?: boolean;
/**
 * Whether the plan content is still streaming (true) or complete (false).
 */
streaming?: boolean;
/**
 * The raw markdown content of the plan file (partial during streaming).
 */
content?: string | null;
/**
 * Normalized markdown content consumed by the frontend.
 */
contentMarkdown?: string | null;
/**
 * The file path where the plan is being written.
 */
filePath?: string | null;
/**
 * The plan title extracted from the first # heading.
 */
title?: string | null;
/**
 * Source quality of the signal.
 */
source?: PlanSource | null;
/**
 * Confidence of the signal.
 */
confidence?: PlanConfidence | null;
/**
 * Agent identifier that produced this plan.
 */
agentId?: string | null;
/**
 * Last update timestamp in milliseconds.
 */
updatedAt?: number | null }

/**
 * Available commands update data.
 */
export type AvailableCommandsData = { availableCommands: AvailableCommand[] }

/**
 * Current mode update data.
 */
export type CurrentModeData = { currentModeId: string }

/**
 * Configuration options update data.
 */
export type ConfigOptionUpdateData = { configOptions: ConfigOptionData[] }

export type ConfigOptionPresentation = "hidden" | "advanced" | "compactReasoning" | "compactSpeed"

/**
 * Configuration option data.
 */
export type ConfigOptionData = { id: string; name: string; category: string; type: string; description?: string | null; currentValue?: JsonValue | null; options?: ConfigOptionValue[]; presentation?: ConfigOptionPresentation }

/**
 * Configuration option value.
 */
export type ConfigOptionValue = { name: string; value: JsonValue; description?: string | null }

/**
 * Explicit reply routing metadata for a canonical interaction.
 */
export type InteractionReplyHandlerKind = "json_rpc" | "http"

/**
 * Backend-owned reply handler metadata for interaction replies.
 */
export type InteractionReplyHandler = { kind: InteractionReplyHandlerKind; requestId: string }

/**
 * Permission request data.
 */
export type PermissionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; permission: string; patterns: string[]; metadata: JsonValue; always: string[]; autoAccepted: boolean; tool?: ToolReference | null }

/**
 * Question request data.
 */
export type QuestionData = { id: string; sessionId: string; jsonRpcRequestId?: number | null; replyHandler?: InteractionReplyHandler | null; questions: QuestionItem[]; tool?: ToolReference | null }

/**
 * Turn error payload for compatibility during rollout.
 */
export type TurnErrorData = string | TurnErrorInfo

/**
 * Structured turn error payload.
 */
export type TurnErrorInfo = { message: string; kind: TurnErrorKind; code?: string | null; source?: TurnErrorSource | null; details?: string | null }

/**
 * Turn error severity.
 */
export type TurnErrorKind = "recoverable" | "fatal"

/**
 * Turn error source.
 */
export type TurnErrorSource = "json_rpc" | "transport" | "process" | "unknown"

/**
 * Embedded resource data
 */
export type EmbeddedResource = {
/**
 * URI of the resource
 */
uri: string;
/**
 * Optional text content
 */
text?: string | null;
/**
 * Optional base64-encoded blob content
 */
blob?: string | null;
/**
 * Optional MIME type
 */
mimeType?: string | null }

/**
 * A single step in a plan.
 */
export type PlanStep = { description: string; status: PlanStepStatus }

/**
 * Plan step status.
 */
export type PlanStepStatus = "pending" | "in_progress" | "completed" | "failed"

/**
 * Plan signal source.
 */
export type PlanSource = "deterministic" | "heuristic"

/**
 * Confidence level for a plan signal.
 */
export type PlanConfidence = "high" | "medium"

/**
 * Tool kind for routing to appropriate UI components.
 */
export type ToolKind = "read" | "read_lints" | "edit" | "execute" | "shell_input" | "search" | "glob" | "fetch" | "web_search" | "think" | "todo" | "question" | "task" | "task_output" | "skill" | "move" | "delete" | "enter_plan_mode" | "exit_plan_mode" | "create_plan" | "tool_search" | "browser" | "computer" | "sql" | "unclassified" | "other"

/**
 * Tool call status.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed"

/**
 * Tool call location.
 */
export type ToolCallLocation = { path: string }

/**
 * Available command with metadata.
 */
export type AvailableCommand = { name: string; description: string; input?: CommandInput | null }

/**
 * Command input hint.
 */
export type CommandInput = {
/**
 * The hint can be a string or array in the protocol; we normalize to string.
 */
hint: string }

/**
 * Tool reference for permission/question requests.
 */
export type ToolReference = { messageId?: string | null; callId: string }

/**
 * Question option.
 */
export type QuestionOption = { label: string; description: string }

/**
 * Question item.
 */
export type QuestionItem = { question: string; header: string; options: QuestionOption[]; multiSelect: boolean }

/**
 * Todo item status.
 */
export type TodoStatus = "pending" | "in_progress" | "completed" | "cancelled"

/**
 * Todo item.
 */
export type TodoItem = { content: string; activeForm: string; status: TodoStatus; startedAt?: number | null; completedAt?: number | null; duration?: number | null }

/**
 * Content block types per ACP protocol specification.
 *
 * @see https://agentclientprotocol.com/protocol/schema#contentblock
 */
export type ContentBlock =
/**
 * Text content block
 */
{ type: "text"; text: string } |
/**
 * Image content block
 */
{ type: "image"; data: string; mimeType: string; uri?: string | null } |
/**
 * Audio content block
 */
{ type: "audio"; data: string; mimeType: string } |
/**
 * Embedded resource content block
 */
{ type: "resource"; resource: EmbeddedResource } |
/**
 * Resource link content block
 */
{ type: "resource_link"; uri: string; name: string; title?: string | null; description?: string | null; mimeType?: string | null; size?: number | null }

/**
 * Skill metadata for skill tool calls.
 */
export type SkillMeta = { description?: string | null; filePath?: string | null }

/**
 * Answered question data from toolUseResult field in JSONL.
 * Stores both the questions and the user's answers.
 */
export type QuestionAnswer = {
/**
 * The questions that were asked
 */
questions: QuestionItem[];
/**
 * Map of question text to answer(s) - value is string for single-select, array for multi-select
 */
answers: Partial<{ [key in string]: JsonValue }> }

/**
 * Error entry stored in replayed session history.
 */
export type StoredErrorMessage = { content: string; code?: string | null; details?: string | null; kind: TurnErrorKind; source?: TurnErrorSource | null }

