// This file was generated by specta. Do not edit this file manually.

/**
 * Response for session plan request.
 * Returned by get_session_plan, get_plan_by_slug, list_plans commands.
 */
export type SessionPlanResponse = {
	/**
	 * Plan slug (filename without .md extension).
	 */
	slug: string;
	/**
	 * Full markdown content of the plan.
	 */
	content: string;
	/**
	 * Plan title (extracted from first # heading).
	 */
	title: string;
	/**
	 * Plan summary (first paragraph after title, if any).
	 */
	summary: string | null;
	/**
	 * Full file path to the plan file (for revealing in file manager).
	 */
	filePath: string | null;
};
