/**
 * Regenerates the graded transcript expectations.
 *
 * Run `bun run qa:bless` after a deliberate change to the projection or to a
 * scenario, read the diff, and commit it. The expectations are a TypeScript
 * module rather than a data file so the test never reads the filesystem, which
 * the repo forbids in tests for good reason: a test that reads a file can pass
 * against a file nobody meant to change.
 */

import { join } from "node:path";
import { authoredScenarios } from "@acepe/qa-scenario";
import * as Effect from "effect/Effect";
import { transcriptJson } from "../src/lib/qa/scenario-transcript.ts";

const TARGET = join(
	import.meta.dir,
	"..",
	"src",
	"lib",
	"qa",
	"__tests__",
	"expected-scenario-transcripts.ts"
);

const HEADER = `/**
 * Generated by \`bun run qa:bless\`. Do not edit by hand.
 *
 * Each entry is the transcript a scenario replay puts on screen, graded in
 * scenario-transcript.test.ts. A diff here means the projection or the scenario
 * changed; both are worth reading before blessing.
 */

import type * as Schema from "effect/Schema";

export const EXPECTED_SCENARIO_TRANSCRIPTS: Readonly<Record<string, Schema.Json>> = `;

const build = Effect.gen(function* () {
	const entries: Array<[string, unknown]> = [];
	for (const scenario of authoredScenarios) {
		entries.push([scenario.meta.name, yield* transcriptJson(scenario)]);
	}
	return Object.fromEntries(entries);
});

const expected = await Effect.runPromise(build);
await Bun.write(TARGET, `${HEADER}${JSON.stringify(expected, null, "\t")};\n`);
console.log(`blessed ${String(Object.keys(expected).length)} scenario transcripts -> ${TARGET}`);
