import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { LinearIconInventoryManifest } from "./types.js";

const packageRoot = resolve(import.meta.dirname);
const defaultInventoryDir = join(packageRoot, "inventory");

export const defaultWebsiteCatalogOutputFile = resolve(
	packageRoot,
	"../../packages/website/src/lib/design-system/linear-icon-catalog.generated.ts",
);

export const defaultUiCatalogOutputFile = resolve(
	packageRoot,
	"../../packages/ui/src/components/icons/linear-icon-catalog.generated.ts",
);

type GenerateLinearIconCatalogOptions = {
	readonly inventoryDir?: string;
	readonly outputFile?: string;
};

type LinearIconCatalogEntry = {
	readonly name: string;
	readonly label: string;
	readonly sourceChunk: string;
	readonly sourceType: string;
	readonly viewBox: string;
	readonly inner: string;
};

function readAttribute(attributes: string, name: string): string {
	const match = attributes.match(new RegExp(`\\b${name}="([^"]*)"`));
	return match?.[1] ?? "";
}

function svgInner(svg: string): string {
	return svg
		.replace(/^<svg\b[^>]*>/s, "")
		.replace(/<\/svg>\s*$/s, "")
		.trim();
}

function formatIconLabel(name: string): string {
	return name
		.split("-")
		.map((part) => {
			if (part.length === 0) {
				return part;
			}
			return `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`;
		})
		.join(" ");
}

function readSvgEntry(svgPath: string, cleanName: string): { viewBox: string; inner: string } {
	const svg = readFileSync(svgPath, "utf8").trim();
	const match = svg.match(/^<svg\b([^>]*)>/s);
	if (!match) {
		throw new Error(`Missing <svg> wrapper in ${svgPath}`);
	}

	const viewBox = readAttribute(match[1] ?? "", "viewBox");
	if (!viewBox) {
		throw new Error(`Missing viewBox in ${svgPath}`);
	}

	return {
		viewBox,
		inner: svgInner(svg),
	};
}

function catalogHash(entries: readonly LinearIconCatalogEntry[]): string {
	const payload = entries.map((entry) => ({
		inner: entry.inner,
		name: entry.name,
		sourceChunk: entry.sourceChunk,
		sourceType: entry.sourceType,
		viewBox: entry.viewBox,
	}));
	return createHash("sha256").update(JSON.stringify(payload)).digest("hex");
}

function parseCliArgs(argv: readonly string[]): GenerateLinearIconCatalogOptions {
	const options: GenerateLinearIconCatalogOptions = {};

	for (let index = 2; index < argv.length; index += 1) {
		const arg = argv[index];
		if (arg === "--output" || arg === "-o") {
			const value = argv[index + 1];
			if (!value) {
				throw new Error("Missing value for --output");
			}
			options.outputFile = value;
			index += 1;
			continue;
		}
		if (arg === "--inventory" || arg === "-i") {
			const value = argv[index + 1];
			if (!value) {
				throw new Error("Missing value for --inventory");
			}
			options.inventoryDir = value;
			index += 1;
			continue;
		}
		throw new Error(`Unknown argument: ${arg}`);
	}

	return options;
}

export function generateLinearIconCatalog(
	options: GenerateLinearIconCatalogOptions = {},
): {
	readonly catalogHash: string;
	readonly iconCount: number;
	readonly outputFile: string;
} {
	const inventoryDir = options.inventoryDir ?? defaultInventoryDir;
	const outputFile = options.outputFile ?? defaultWebsiteCatalogOutputFile;
	const manifestPath = join(inventoryDir, "manifest.json");
	const manifest = JSON.parse(
		readFileSync(manifestPath, "utf8"),
	) as LinearIconInventoryManifest;

	const entries: LinearIconCatalogEntry[] = manifest.icons
		.filter((icon) => icon.duplicateOf === null)
		.map((icon) => {
			const svgPath = join(inventoryDir, icon.svgFile);
			const svgEntry = readSvgEntry(svgPath, icon.cleanName);
			return {
				name: icon.cleanName,
				label: formatIconLabel(icon.cleanName),
				sourceChunk: icon.sourceChunk,
				sourceType: icon.sourceType,
				viewBox: svgEntry.viewBox,
				inner: svgEntry.inner,
			};
		})
		.sort((left, right) => left.name.localeCompare(right.name));

	const hash = catalogHash(entries);
	const iconNameLines = entries.map((entry) => `\t${JSON.stringify(entry.name)},`);
	const iconDataLines = entries.map(
		(entry) =>
			`\t${JSON.stringify(entry.name)}: { viewBox: ${JSON.stringify(entry.viewBox)}, inner: ${JSON.stringify(entry.inner)}, label: ${JSON.stringify(entry.label)}, sourceChunk: ${JSON.stringify(entry.sourceChunk)}, sourceType: ${JSON.stringify(entry.sourceType)} },`,
	);
	const libraryLines = entries.map(
		(entry) =>
			`\t{ name: ${JSON.stringify(entry.name)}, label: ${JSON.stringify(entry.label)}, sourceChunk: ${JSON.stringify(entry.sourceChunk)}, sourceType: ${JSON.stringify(entry.sourceType)}, fileName: ${JSON.stringify(`${entry.name}.svg`)} },`,
	);

	const output = `// Generated by scripts/linear-icons/generate-website-icon-catalog.ts.
// Source: scripts/linear-icons/inventory (${entries.length} unique Linear-derived icons).

export type LinearIconCatalogData = {
\treadonly viewBox: string;
\treadonly inner: string;
\treadonly label: string;
\treadonly sourceChunk: string;
\treadonly sourceType: string;
};

export type LinearIconLibraryEntry = {
\treadonly name: LinearIconName;
\treadonly label: string;
\treadonly sourceChunk: string;
\treadonly sourceType: string;
\treadonly fileName: string;
};

export const linearIconCatalogHash = ${JSON.stringify(hash)};

export const linearIconNames = [
${iconNameLines.join("\n")}
] as const;

export type LinearIconName = (typeof linearIconNames)[number];

export const linearIconData: Record<LinearIconName, LinearIconCatalogData> = {
${iconDataLines.join("\n")}
};

export const linearIconLibrary: readonly LinearIconLibraryEntry[] = [
${libraryLines.join("\n")}
];
`;

	mkdirSync(resolve(outputFile, ".."), { recursive: true });
	writeFileSync(outputFile, output);

	return {
		catalogHash: hash,
		iconCount: entries.length,
		outputFile,
	};
}

/** @deprecated Use generateLinearIconCatalog instead. */
export const generateWebsiteIconCatalog = generateLinearIconCatalog;

if (import.meta.main) {
	const result = generateLinearIconCatalog(parseCliArgs(process.argv));
	console.log(`Generated ${result.iconCount} Linear icons at ${result.outputFile}`);
	console.log(`Catalog hash: ${result.catalogHash}`);
}
